services:
  ledger-api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_PATH: ./cmd/ledger-api
    container_name: go-ledger-api
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      PORT: "8080"
      DATABASE_URL: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?sslmode=disable"
      REDIS_ADDR: "redis:6379"
      RABBITMQ_URL: "amqp://${RABBITMQ_USER:-ledger}:${RABBITMQ_PASSWORD:-ledger}@rabbitmq:5672/"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "wget -q -O /dev/null http://127.0.0.1:8080/api/v1/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    networks:
      - ledger-net

  ledger-admin:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_PATH: ./cmd/ledger-admin
    container_name: go-ledger-admin
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      PORT: "8081"
      DATABASE_URL: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?sslmode=disable"
      TENANT_ADMIN_KEY: ${TENANT_ADMIN_KEY:-WX5TczRsQnCk7k8k9AXbsW5czRsQnCkg}
      TENANT_SCHEMA_MIGRATION_PATH: "migrations/0002_init_tenant_schema.sql"
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "wget -q -O /dev/null http://127.0.0.1:8081/api/v1/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    networks:
      - ledger-net

  ledger-worker:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_PATH: ./cmd/ledger-worker
    container_name: go-ledger-worker
    environment:
      DATABASE_URL: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?sslmode=disable"
      REDIS_ADDR: "redis:6379"
      RABBITMQ_URL: "amqp://${RABBITMQ_USER:-ledger}:${RABBITMQ_PASSWORD:-ledger}@rabbitmq:5672/"
      RABBITMQ_USER: "${RABBITMQ_USER:-ledger}"
      RABBITMQ_PASSWORD: "${RABBITMQ_PASSWORD:-ledger}"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - ledger-net

  postgres:
    image: postgres:18.3-alpine
    container_name: go-ledger-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-ledger}
      POSTGRES_USER: ${POSTGRES_USER:-ledger}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-StrongPa55word123!}
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER:-ledger} -d ${POSTGRES_DB:-ledger} -h localhost -p 5432",
        ]
      interval: 10s
      timeout: 5s
      retries: 10
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # Run shared/public migration automatically on first DB initialization.
      - ./migrations/0001_init_public.sql:/docker-entrypoint-initdb.d/0001_init_public.sql:ro
    networks:
      - ledger-net

  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    container_name: go-ledger-rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER:-ledger}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD:-ledger}
    healthcheck:
      test: ["CMD-SHELL", "rabbitmq-diagnostics -q ping"]
      interval: 10s
      timeout: 5s
      retries: 10
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - ledger-net

  redis:
    image: redis:8-alpine
    container_name: go-ledger-redis
    restart: unless-stopped
    command: ["redis-server", "--appendonly", "yes"]
    # ports:
    #   - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 10
    volumes:
      - redis_data:/data
    networks:
      - ledger-net

volumes:
  postgres_data:
  rabbitmq_data:
  redis_data:

networks:
  ledger-net:
